apiVersion: v2
name: zitadel
description: A Helm chart for ZITADEL v2
type: application
version: 0.1.1
appVersion: "v2.0.0-v2-alpha.19-amd64"
icon: https://zitadel.zitadel.cloud/ui/login/resources/themes/zitadel/logo-dark.svg
dependencies:
- name: cockroachdb
  version: ~8.0.0
  repository: https://charts.cockroachdb.com/
  condition: cockroachdb.enabled
maintainers: # (optional)
- name: ZITADEL Staff
  email: support@zitadel.com
  url: https://zitadel.com
