name: 'Release Charts'

on:
  push:
    branches:
      - 'main'

jobs:
  release:

    runs-on: 'ubuntu-20.04'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v3'

    - id: 'configure-git'
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - id: 'release'
      uses: 'helm/chart-releaser-action@v1.1.0'
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

