name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  job_id:

    runs-on: ubuntu-20.04

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v3'

    - id: 'package'
      run: |
        docker run -it --rm --volume $(pwd):/in --volume $(pwd)/.artifacts:/out alpine/helm:3.9.0 package /in --destination /out
        docker run -it --rm --volume $(pwd)/.artifacts:/out alpine/helm:3.9.0 repo index /out

    - id: 'repo-auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - id: 'repo-upload'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: '.artifacts'
        destination: 'zitadel-charts/zitadel'
