name: 'Test Charts'

on: 'pull_request'

jobs:
  release:

    runs-on: 'ubuntu-20.04'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v3'
      with:
        fetch-depth: 0

    - id: 'set-up-helm'
      uses: 'azure/setup-helm@v1'
      with:
        version: 'v3.8.1'

    - id: 'set-up-python'
      uses: 'actions/setup-python@v2'
      with:
        python-version: 3.7

    - id: 'set-up-chart-testing'
      uses: 'helm/chart-testing-action@v2.2.1'
      with:
        version: 'v3.6.0'

    - id: 'list-changed'
      run: |
        changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
        if [[ -n "$changed" ]]; then
          echo "::set-output name=changed::true"
        fi

    - id: 'add-cockroachdb-repo'
      run: 'helm repo add cockroachdb https://charts.cockroachdb.com/'

    - id: 'lint'
      run: 'ct lint --target-branch ${{ github.event.repository.default_branch }}'

    - name: 'create-kind'
      uses: 'helm/kind-action@v1.2.0'
      if: steps.list-changed.outputs.changed == 'true'

    - name: 'install'
      run: 'ct install --all --helm-extra-set-args "--set=zitadel.masterkey=\"$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32)\" --set=zitadel.configmapConfig.ExternalDomain=\"test.domain\" --set=zitadel.secretConfig.Database.User.Password=\"$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32)\""'

